language: node_js
node_js:
- stable
deploy:
  provider: heroku
  app: mapgo-front
  api_key:
    secure: blRzAzcOZDBgEB4fpWNie8DOQ4+RPXCzPyElAiuj2ukhPYAn6U/zBz4fu2c/B6jvRQSOYX9ho4t8tuEQHpPtMqgNvn+jJ4YobLOWj7UGf21TIf8XSEuFpDLY89tszA9/5AfPTRhNDldrWS+P5t82QwyxYPmk+Po7IDn/ngMMl66iH35LSha16q7MBgAepKMv1NTjgeQyXvSl4XJW04lRC4+PL487cFPa1GphxSFfUJXglnJlDrNrSLgmAgVd6V7HlMssvYnabdLiowiV/gmHEUiLW5Z8KoqqshHPD0PCmexuhlbQpj2+gSLe2p3kkGl0iqNK0h6GT4hU/3HDX9U7h+ZHaXVl3NPU0K0IrPaAQp7EuZ9BlQ50KEreh/dpd5BE/7rzT53hLlXjQHuF71I+FDlrQqhwSfPW5iZLs3g+fIAfbzmnpc9QIe02Zk0g1G4Kj/1g+3Vdw6Wnb0EARD0g0eMRHC62Z6A0vYbxbQX2bQYagdw9m98BXiX2P2eSVswFauoD5PDKIta9ImBJYL8z2CFLTZNPGEw0DrjrQb43yYrfIu8qYgBWUdAb8l6l1YF0OHxya463XwGFCYKwm4ktBHwjIG5nqjl4osPK4+YmyJEfF0FFsYvlxXoQkeMcQmSkVV1Bv35qO246iorjj7J8HTOBAo0xMVg3LDlidXDdlBI=
